server:
  port: 8080
  servlet-path: /ebook/manager
spring:
  platform:
    name: ebook-manager
  profiles:
    active: dev
  application:
    name: ebook-manager
  logback:
    max-history: 100
    devLevel: info
    testLevel: info
    prodLevel: info
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ebook-manager?useAffectedRows=true&allowMultiQueries=true&autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimeZone=GTM%2B8
    username: root
    password: root123
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 40
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 100000
      time-between-eviction-runs-millis: 60000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000

http-pool:
  max-total: 100
  default-max-per-route: 20
  connect-timeout: 1000
  connection-request-timeout: 3000
  socket-timeout: 5000
  validate-after-inactivity: 7000
  async: true

logging:
  config: classpath:logback-spring.xml

mybatis:
  type-aliases-package: com.henanuniversity.wangqi.entity
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
