package com.henanuniversity.wangqi.entity.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book_classify
 */
public class BookClassifyDto {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classify.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classify.name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classify.id
     *
     * @return the value of book_classify.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classify.id
     *
     * @param id the value for book_classify.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classify.name
     *
     * @return the value of book_classify.name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classify.name
     *
     * @param name the value for book_classify.name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}