package com.henanuniversity.wangqi.entity.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book_recommend
 */
public class BookRecommendDto {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   图书id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long bookId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend.create_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_recommend.update_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend.id
     *
     * @return the value of book_recommend.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend.id
     *
     * @param id the value for book_recommend.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend.book_id
     *
     * @return the value of book_recommend.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend.book_id
     *
     * @param bookId the value for book_recommend.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend.create_time
     *
     * @return the value of book_recommend.create_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend.create_time
     *
     * @param createTime the value for book_recommend.create_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_recommend.update_time
     *
     * @return the value of book_recommend.update_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_recommend.update_time
     *
     * @param updateTime the value for book_recommend.update_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}