package com.henanuniversity.wangqi.entity.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book_borrow
 */
public class BookBorrowDto {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户学号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.account
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private String account;

    /**
     * Database Column Remarks:
     *   图书id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long bookId;

    /**
     * Database Column Remarks:
     *   图书书名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.book_name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private String bookName;

    /**
     * Database Column Remarks:
     *   借阅日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.borrow_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Date borrowTime;

    /**
     * Database Column Remarks:
     *   借阅时长，单位天
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.keep
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Integer keep;

    /**
     * Database Column Remarks:
     *   是否归还，0：否 1 ：是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.return
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Integer return;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.create_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_borrow.update_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.id
     *
     * @return the value of book_borrow.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.id
     *
     * @param id the value for book_borrow.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.account
     *
     * @return the value of book_borrow.account
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.account
     *
     * @param account the value for book_borrow.account
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.book_id
     *
     * @return the value of book_borrow.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.book_id
     *
     * @param bookId the value for book_borrow.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.book_name
     *
     * @return the value of book_borrow.book_name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.book_name
     *
     * @param bookName the value for book_borrow.book_name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.borrow_time
     *
     * @return the value of book_borrow.borrow_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Date getBorrowTime() {
        return borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.borrow_time
     *
     * @param borrowTime the value for book_borrow.borrow_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setBorrowTime(Date borrowTime) {
        this.borrowTime = borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.keep
     *
     * @return the value of book_borrow.keep
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Integer getKeep() {
        return keep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.keep
     *
     * @param keep the value for book_borrow.keep
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setKeep(Integer keep) {
        this.keep = keep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.return
     *
     * @return the value of book_borrow.return
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Integer getReturn() {
        return return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.return
     *
     * @param return the value for book_borrow.return
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setReturn(Integer return) {
        this.return = return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.create_time
     *
     * @return the value of book_borrow.create_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.create_time
     *
     * @param createTime the value for book_borrow.create_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_borrow.update_time
     *
     * @return the value of book_borrow.update_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_borrow.update_time
     *
     * @param updateTime the value for book_borrow.update_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}