package com.henanuniversity.wangqi.entity.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book_collect
 */
public class BookCollectDto {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_collect.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户学号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_collect.account
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private String account;

    /**
     * Database Column Remarks:
     *   图书书名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_collect.book_name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private String bookName;

    /**
     * Database Column Remarks:
     *   图书id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_collect.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long bookId;

    /**
     * Database Column Remarks:
     *   收藏时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_collect.coll_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Date collTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_collect.id
     *
     * @return the value of book_collect.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_collect.id
     *
     * @param id the value for book_collect.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_collect.account
     *
     * @return the value of book_collect.account
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_collect.account
     *
     * @param account the value for book_collect.account
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_collect.book_name
     *
     * @return the value of book_collect.book_name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_collect.book_name
     *
     * @param bookName the value for book_collect.book_name
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_collect.book_id
     *
     * @return the value of book_collect.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_collect.book_id
     *
     * @param bookId the value for book_collect.book_id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_collect.coll_time
     *
     * @return the value of book_collect.coll_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Date getCollTime() {
        return collTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_collect.coll_time
     *
     * @param collTime the value for book_collect.coll_time
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setCollTime(Date collTime) {
        this.collTime = collTime;
    }
}