package com.henanuniversity.wangqi.entity.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book_stock
 */
public class BookStockDto {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_stock.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_stock.address
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_stock.id
     *
     * @return the value of book_stock.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_stock.id
     *
     * @param id the value for book_stock.id
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_stock.address
     *
     * @return the value of book_stock.address
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_stock.address
     *
     * @param address the value for book_stock.address
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}