package com.henanuniversity.wangqi.dao;

import com.henanuniversity.wangqi.entity.dto.BookCollectDto;

public interface BookCollectDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_collect
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_collect
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insert(BookCollectDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_collect
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insertSelective(BookCollectDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_collect
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    BookCollectDto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_collect
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKeySelective(BookCollectDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_collect
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKey(BookCollectDto record);
}