package com.henanuniversity.wangqi.dao;

import com.henanuniversity.wangqi.entity.dto.BookBorrowDto;

public interface BookBorrowDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insert(BookBorrowDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insertSelective(BookBorrowDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    BookBorrowDto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKeySelective(BookBorrowDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKey(BookBorrowDto record);
}