package com.henanuniversity.wangqi.dao;

import com.henanuniversity.wangqi.entity.dto.BookRecommendDto;

public interface BookRecommendDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_recommend
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_recommend
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insert(BookRecommendDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_recommend
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insertSelective(BookRecommendDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_recommend
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    BookRecommendDto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_recommend
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKeySelective(BookRecommendDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_recommend
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKey(BookRecommendDto record);
}