package com.henanuniversity.wangqi.dao;

import com.henanuniversity.wangqi.entity.dto.BookStockDto;

public interface BookStockDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insert(BookStockDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insertSelective(BookStockDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    BookStockDto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKeySelective(BookStockDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKey(BookStockDto record);
}