package com.henanuniversity.wangqi.dao;

import com.henanuniversity.wangqi.entity.dto.BookClassifyDto;

public interface BookClassifyDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insert(BookClassifyDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insertSelective(BookClassifyDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    BookClassifyDto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKeySelective(BookClassifyDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKey(BookClassifyDto record);
}