package com.henanuniversity.wangqi.dao;

import com.henanuniversity.wangqi.entity.dto.UserDto;

public interface UserDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insert(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int insertSelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    UserDto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKeySelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Apr 01 22:43:30 CST 2021
     */
    int updateByPrimaryKey(UserDto record);
}